{"name": "test_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <api_testing_framework.cases.test_case.TestCase object at 0x104268e30>\n\n    def test_c(self):\n>       assert 1 > 2\nE       assert 1 > 2\n\ncases/test_case.py:36: AssertionError"}, "start": 1722253934582, "stop": 1722253934583, "uuid": "dfb03160-e568-467b-ae04-3a0b9a90c186", "historyId": "f0bdbd8b723e0e885b8379145f3e0a3d", "testCaseId": "f0bdbd8b723e0e885b8379145f3e0a3d", "fullName": "cases.test_case.TestCase#test_c", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "XiaofeideMacBook-Pro.local"}, {"name": "thread", "value": "18049-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_case"}]}