{"name": "test_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <api_testing_framework.cases.test_case.TestCase object at 0x1061c1d60>\n\n    def test_c(self):\n>       assert 1 > 2\nE       assert 1 > 2\n\ncases/test_case.py:36: AssertionError"}, "start": 1722247990758, "stop": 1722247990758, "uuid": "a5f718c0-5741-475b-aa0e-2637218b25aa", "historyId": "f0bdbd8b723e0e885b8379145f3e0a3d", "testCaseId": "f0bdbd8b723e0e885b8379145f3e0a3d", "fullName": "cases.test_case.TestCase#test_c", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "XiaofeideMacBook-Pro.local"}, {"name": "thread", "value": "11453-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_case"}]}