{"name": "test_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <api_testing_framework.cases.test_case.TestCase object at 0x105fcc920>\n\n    def test_c(self):\n>       assert 1 > 2\nE       assert 1 > 2\n\ntest_case.py:36: AssertionError"}, "attachments": [{"name": "stdout", "source": "440033b2-d49a-40f6-b9d7-ee07c059ef8d-attachment.txt", "type": "text/plain"}], "start": 1722246157960, "stop": 1722246157960, "uuid": "b94d925b-427a-430a-87ea-c9093eb889d7", "historyId": "f0bdbd8b723e0e885b8379145f3e0a3d", "testCaseId": "f0bdbd8b723e0e885b8379145f3e0a3d", "fullName": "cases.test_case.TestCase#test_c", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "XiaofeideMacBook-Pro.local"}, {"name": "thread", "value": "10087-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_case"}]}